### PR TITLE
Update schema for cylc play

### PR DESCRIPTION
**Pull request by MetRonnie**
This is a small change with no associated Issue. Belated companion to https://github.com/cylc/cylc-flow/pull/4076

Updates old hold options in the cylc-play schema. 

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [ ] Appropriate tests are included (unit and/or functional).
- [x] Appropriate change log entry included.
- [x] No documentation update required.
- [x] No dependency changes.

### CODE REVIEW

**Comment by MetRonnie** [comment]
Not sure if/how to test this

**Review by datamel — APPROVED** [review]
Thanks Ronnie. In terms of testing, I'm a bit stumped. I wonder if we could do some sort of schema query from cylc-flow and ui-server and compare.

**Review by kinow — COMMENTED** [review]
Code looks good! I think similar code was not tested too, as we'd need some fixtures or a complete functional test I think. But let me spend a few minutes reading the tests & code to confirm :+1:

**Review by kinow — APPROVED** [review]
Couldn't find other tests that could be used as reference for this. I've created a follow-up for this: https://github.com/cylc/cylc-uiserver/issues/243

**Pull request merged**
