### PR TITLE
Bump cylc-flow version

### PR DESCRIPTION
**Pull request by MetRonnie**
If the next uiserver release is a minor rather than maintenance one, then doesn't it need to have a dependency on the next cylc-flow minor release?

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Any dependency changes applied to `setup.cfg`.
- [x] Does not need tests 
- [x] No change log entry required
- [x] No documentation update required.

### CODE REVIEW

**Comment by hjoliver** [comment]
> If the next uiserver release is a minor rather than maintenance one, then doesn't it need to have a dependency on the next cylc-flow minor release?

But I suppose we can't be sure yet that the next UIS release will not be a maintenance release (we might find a bug requiring a quick fix...).

**Comment by MetRonnie** [comment]
I say we branch off the 1.1.0 tag in that case

**Comment by oliver-sanders** [comment]
> **If the next uiserver release is a minor rather than maintenance one, then doesn't it need to have a dependency on the next cylc-flow minor release?**

Yes, this is on the cylc-admin issue template (metadata section) but got missed this time around. The same also applies to cylc-rose.

https://github.com/cylc/cylc-admin/issues/157

**Comment by oliver-sanders** [comment]
(Note that the tests are run against the cylc-flow master branch)

**Comment by MetRonnie** [comment]
Actually as there's currently the dependency on `cylc-flow==8.0.*`, it's currently installing cylc-flow master, then uninstalling and replacing with 8.0.1
https://github.com/cylc/cylc-uiserver/blob/5286d488c4a60afa82deba1d92dff400b8efb97b/.github/workflows/test.yml#L33-L36

**Review by hjoliver — APPROVED** [review]

**Pull request merged**
