### PR TITLE
DataStoreMgr - use single thread pool

### LINKED ISSUE #327: data_store_mgr: central thread pool
Currently a new thread pool is created for every subscription.

https://github.com/cylc/cylc-uiserver/blob/ab9268d8b8b1de05ca82a7d9d120c6e19ca222e7/cylc/uiserver/data_store_mgr.py#L144

We should be able to use a single thread pool for all subscriptions.

This may have a small efficiency bonus in avoiding the unnecessary closing / opening of threads in some situations.

**Pull requests welcome!**

### PR DESCRIPTION
**Pull request by MetRonnie**
These changes close #327

Use a single thread pool for all subscriptions instead of one for each.

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Any dependency changes applied to `setup.cfg`.
- [x] Does not need tests 
- [x] No change log entry required (invisible to users).
- [x] No documentation update required.

### CODE REVIEW

**Comment by MetRonnie** [comment]
Mypy errors also on master - #365

**Review by wxtim — APPROVED** [review]
Seems sensible enough, and tried locally.

**Review by wxtim — APPROVED** [review]

**Comment by MetRonnie** [comment]
Dammit, it's just the codecov upload that's failing: https://github.com/cylc/cylc-uiserver/runs/6829748627?check_suite_focus=true

**Comment by MetRonnie** [comment]
Merging with 2 approvals + passing CI

**Pull request merged**
