### PR TITLE
Fix bug with SQL query for analysis view

### PR DESCRIPTION
**Pull request by ChrisPaulBennett**
**Check List**

- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [ ] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Applied any dependency changes to both `setup.cfg` (and `conda-environment.yml` if present).
- [x] Tests are included (or explain why tests are not needed).
- [x] `CHANGES.md` entry included if this is a change that can affect users
- [x] [Cylc-Doc](https://github.com/cylc/cylc-doc) pull request opened if required at cylc/cylc-doc/pull/XXXX.
- [x] If this is a bug fix, PR should be raised against the relevant `?.?.x` branch.

### CODE REVIEW

**Comment by oliver-sanders** [comment]
Hi there, thanks for this fix.

You've merged master into this branch, but the PR is being raised against 1.3.x, as a result there are a bunch of unrelated commits from the 1.4.0 branch (master) showing on this PR.

The easiest way to proceed is probably to cherry-pick those commits onto 1.3.x e.g:

```console
$ git fetch upstream
$ git checkout -b fix-sql-bug upstream/1.3.x
$ git cherry-pick 3e80eedb25a311c3ecc5e9fae5fe450d56fea930
$ git cherry-pick 6b3e99fcaa71f3cf945ef3fd9ff4c9ca529b1932
$ git cherry-pick 9b8b94d93a2f92c9d448629e70875ffb313b93c2
```

Check the diff is as expected:

```
$ git diff upstream/1.3.x
```

You can avoid re-opening this PR by pushing to origin/master e.g:

```
# override your remote master with this branch
$ git push -f origin HEAD:master
```

**Comment by MetRonnie** [comment]
Thanks, can you just extract commit 3e80eedb25a311c3ecc5e9fae5fe450d56fea930? May have to create a feature branch and open a new PR
```
$ git checkout -b sql-fix upstream/1.3.x # (if the remote is called upstream)
$ git cherry-pick 3e80eedb25a311c3ecc5e9fae5fe450d56fea930
```

**Review by MetRonnie — APPROVED** [review]
LGTM, though I'm not sure how to test/reproduce the bug, may need @oliver-sanders to review too

**Comment by oliver-sanders** [comment]
> I'm not sure how to test/reproduce the bug, may need @oliver-sanders to review too


I think this should do it, try viewing a workflow with:

* A single failed task `script = false`.
  * The analysis view should not list any times for this task (`run status != 0`).
* Then broadcast `script = sleep 60` and re-trigger the task.
  * The task should now show in the analysis view.
  * The run time should be ~60s not ~30s (because the failed task has been excluded).

**Comment by MetRonnie** [comment]
Ok, tested, reproduced bug on 1.3.x but all good on this branch

**Pull request merged**
