### PR TITLE
Terminology: suite to workflow.

### PR DESCRIPTION
**Pull request by hjoliver**
This is a small change with no associated Issue.

UIS sibling of https://github.com/cylc/cylc-flow/pull/4174

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Does not need tests (just internal name changes).
- [x] No change log entry required (why? e.g. invisible to users).
- [x] No documentation update required.
- [x] No dependency changes.

### CODE REVIEW

**Review by kinow — APPROVED** [review]
Code looks good to me.

`mypy` unhappy with some imported code, but I think it depends on the sibling PR being merged for the error to go away @hjoliver ? 

```
cylc/uiserver/workflows_mgr.py:37: error: Module 'cylc.flow.network.client' has no attribute 'WorkflowRuntimeClient'
```

**Comment by kinow** [comment]
Just grep'ed `src` in Cylc UI, I think it has <10 occurrences of `-i "suite"`.

**Comment by hjoliver** [comment]
PR coming for that too

**Comment by hjoliver** [comment]
(This branch tested OK with cylc/cylc-flow/pull/4174 and cylc/cylc-ui/pull/646)

**Review by datamel — COMMENTED** [review]
I have made a note about back compatibility on the sibling PR (https://github.com/cylc/cylc-flow/pull/4174#pullrequestreview-637649271)
Other than that, I have read the changes and am happy with the PR

**Comment by hjoliver** [comment]
> I have made a note about back compatibility on the sibling PR

Last commit on the cylc-flow PR fixes this.

**Comment by hjoliver** [comment]
(The problem comes into the UIS via the cylc-flow scan code).

**Review by MetRonnie — APPROVED** [review]

**Review by datamel — APPROVED** [review]
Now the cylc-flow fix in, I'm marking as approved.

**Comment by hjoliver** [comment]
Tests pass since the cylc-flow PR merged :+1:

**Pull request merged**
