### PR TITLE
Move Cylc Flow to the top of dependencies list

### PR DESCRIPTION
**Pull request by kinow**
This is a small change with no associated Issue.

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Does not need tests (why? build change).
- [x] No change log entry required (why? e.g. invisible to users).
- [x] No documentation update required.

### CODE REVIEW

**Comment by kinow** [comment]
This change puts Cylc Flow as the first dependency in our `setup.py`. This forces other dependencies that do not pin versions to use whatever Cylc Flow requires.

i.e. if `jupyterhub` allows **any** version of jinja2, but Cylc needs at least 2.10, but not 2.11, then whoever comes first in `setup.py` is processed first. Meaning that if there is a version `jinja2==2.99`, even though Cylc Flow may break, if `jupyterhub` is listed first, that's the version we would get here.

To review it, try installing from `master` today. As jinja2 2.11.1 was released on Jan 30th, your virtual environment should fail to install it (unless you have some cached versions...)

```bash
Requirement already satisfied: cffi!=1.11.3,>=1.8 in ./venv/lib/python3.7/site-packages (from cryptography>=2.8->pyopenssl->certipy>=0.1.2->jupyterhub==1.0.*->cylc-uiserver==0.1) (1.13.2)
Requirement already satisfied: pycparser in ./venv/lib/python3.7/site-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.8->pyopenssl->certipy>=0.1.2->jupyterhub==1.0.*->cylc-uiserver==0.1) (2.19)
Installing collected packages: jinja2, jupyterhub, cylc-uiserver
  Attempting uninstall: cylc-uiserver
    Found existing installation: cylc-uiserver 0.1
    Uninstalling cylc-uiserver-0.1:
      Successfully uninstalled cylc-uiserver-0.1
  Running setup.py develop for cylc-uiserver
Successfully installed cylc-uiserver jinja2-2.10.3 jupyterhub-1.0.0
```

It worked for me after this change.

**Comment by kinow** [comment]
**Additional context**

Started the day by syncing repositories, and re-creating virtual environments.

Unfortunately cylc-uiserver was not being installed successfully:

```bash
Processing /home/kinow/.cache/pip/wheels/f2/9a/90/de94f8556265ddc9d9c8b271b0f63e57b26fb1d67a45564511/pycparser-2.19-py2.py3-none-any.whl
Building wheels for collected packages: cylc-flow
  Building wheel for cylc-flow (setup.py) ... done
  Created wheel for cylc-flow: filename=cylc_flow-8.0a1-py3-none-any.whl size=667551 sha256=f8fcd8750b8d70b2c378a3e82951c179f295d86255be6d8cdf8a240b6df2f225
  Stored in directory: /tmp/pip-ephem-wheel-cache-n0lz8ncf/wheels/5e/9d/69/a6c2eb6e6e159d55e4d8f1d93971f5af49188c8ccfc00c7b97
Successfully built cylc-flow
ERROR: cylc-flow 8.0a1 has requirement jinja2<2.11.0,>=2.10.1, but you'll have jinja2 2.11.1 which is incompatible.
Installing collected packages: certifi, urllib3, idna, chardet, requests, markupsafe, jinja2, oauthlib, SQLAlchemy, python-editor, Mako, six, python-dateutil, alembic, prometheus-client, async-generator, entrypoints, pamela, ipython-genutils, decorator, traitlets, pycparser, cffi, cryptography, pyopenssl, certipy, tornado, jupyterhub, promise, rx, graphql-core, graphql-relay, aniso8601, graphene, werkzeug, graphene-tornado, colorama, ansimarkup, metomi-isodatetime, protobuf, pyzmq, click, cylc-flow, graphql-ws, cylc-uiserver
  Running setup.py develop for cylc-uiserver
Successfully installed Mako-1.1.1 SQLAlchemy-1.3.13 alembic-1.3.3 aniso8601-7.0.0 ansimarkup-1.4.0 async-generator-1.10 certifi-2019.11.28 certipy-0.1.3 cffi-1.13.2 chardet-3.0.4 click-7.0 colorama-0.4.3 cryptography-2.8 cylc-flow-8.0a1 cylc-uiserver decorator-4.4.1 entrypoints-0.3 graphene-2.1.8 graphene-tornado-2.1.1 graphql-core-2.3.1 graphql-relay-2.0.1 graphql-ws-0.3.0 idna-2.8 ipython-genutils-0.2.0 jinja2-2.11.1 jupyterhub-1.0.0 markupsafe-1.1.1 metomi-isodatetime-1!2.0.1 oauthlib-3.1.0 pamela-1.0.0 prometheus-client-0.7.1 promise-2.3 protobuf-3.11.2 pycparser-2.19 pyopenssl-19.1.0 python-dateutil-2.8.1 python-editor-1.0.4 pyzmq-18.0.2 requests-2.22.0 rx-1.6.1 six-1.14.0 tornado-6.0.3 traitlets-4.3.3 urllib3-1.25.8 werkzeug-0.12.2

```

Using `pipdeptree`, it's possible to see the whole dependency tree, which shows the same warning, but we can now see why Jinja 2.11 was installed. It was because of `jupyterhub` requiring `Any`, and due to a new release of `jinja2` 2.11.1 from 30th January.

```bash
$ pipdeptree
Warning!!! Possibly conflicting dependencies found:
* cylc-flow==8.0a1
 - jinja2 [required: >=2.10.1,<2.11.0, installed: 2.11.1]
------------------------------------------------------------------------
cylc-uiserver==0.1
  - cylc-flow [required: Any, installed: 8.0a1]
    - ansimarkup [required: >=1.0.0, installed: 1.4.0]
      - colorama [required: Any, installed: 0.4.3]
    - click [required: >=7.0, installed: 7.0]
    - colorama [required: ==0.4.*, installed: 0.4.3]
    - graphene [required: >=2.1,<3, installed: 2.1.8]
      - aniso8601 [required: >=3,<=7, installed: 7.0.0]
      - graphql-core [required: >=2.1,<3, installed: 2.3.1]
        - promise [required: >=2.3,<3, installed: 2.3]
          - six [required: Any, installed: 1.14.0]
        - rx [required: >=1.6,<2, installed: 1.6.1]
        - six [required: >=1.10.0, installed: 1.14.0]
      - graphql-relay [required: >=2,<3, installed: 2.0.1]
        - graphql-core [required: >=2.2,<3, installed: 2.3.1]
          - promise [required: >=2.3,<3, installed: 2.3]
            - six [required: Any, installed: 1.14.0]
          - rx [required: >=1.6,<2, installed: 1.6.1]
          - six [required: >=1.10.0, installed: 1.14.0]
        - promise [required: >=2.2,<3, installed: 2.3]
          - six [required: Any, installed: 1.14.0]
        - six [required: >=1.12, installed: 1.14.0]
      - six [required: >=1.10.0,<2, installed: 1.14.0]
    - jinja2 [required: >=2.10.1,<2.11.0, installed: 2.11.1]
      - MarkupSafe [required: >=0.23, installed: 1.1.1]
    - markupsafe [required: ==1.1.*, installed: 1.1.1]
    - metomi-isodatetime [required: ==1!2.0.*, installed: 1!2.0.1]
    - protobuf [required: ==3.11.*, installed: 3.11.2]
      - setuptools [required: Any, installed: 45.1.0]
      - six [required: >=1.9, installed: 1.14.0]
    - pyzmq [required: ==18.0.*, installed: 18.0.2]
  - graphene-tornado [required: ==2.1.*, installed: 2.1.1]
    - graphene [required: >=2.1,<3, installed: 2.1.8]
      - aniso8601 [required: >=3,<=7, installed: 7.0.0]
      - graphql-core [required: >=2.1,<3, installed: 2.3.1]
        - promise [required: >=2.3,<3, installed: 2.3]
          - six [required: Any, installed: 1.14.0]
        - rx [required: >=1.6,<2, installed: 1.6.1]
        - six [required: >=1.10.0, installed: 1.14.0]
      - graphql-relay [required: >=2,<3, installed: 2.0.1]
        - graphql-core [required: >=2.2,<3, installed: 2.3.1]
          - promise [required: >=2.3,<3, installed: 2.3]
            - six [required: Any, installed: 1.14.0]
          - rx [required: >=1.6,<2, installed: 1.6.1]
          - six [required: >=1.10.0, installed: 1.14.0]
        - promise [required: >=2.2,<3, installed: 2.3]
          - six [required: Any, installed: 1.14.0]
        - six [required: >=1.12, installed: 1.14.0]
      - six [required: >=1.10.0,<2, installed: 1.14.0]
    - Jinja2 [required: >=2.10.1, installed: 2.11.1]
      - MarkupSafe [required: >=0.23, installed: 1.1.1]
    - six [required: >=1.10.0, installed: 1.14.0]
    - tornado [required: >=5.1.0, installed: 6.0.3]
    - werkzeug [required: ==0.12.2, installed: 0.12.2]
  - graphql-core [required: >=2.1,<3, installed: 2.3.1]
    - promise [required: >=2.3,<3, installed: 2.3]
      - six [required: Any, installed: 1.14.0]
    - rx [required: >=1.6,<2, installed: 1.6.1]
    - six [required: >=1.10.0, installed: 1.14.0]
  - graphql-ws [required: ==0.3.*, installed: 0.3.0]
    - graphql-core [required: >=2.0<3, installed: 2.3.1]
      - promise [required: >=2.3,<3, installed: 2.3]
        - six [required: Any, installed: 1.14.0]
      - rx [required: >=1.6,<2, installed: 1.6.1]
      - six [required: >=1.10.0, installed: 1.14.0]
  - jupyterhub [required: ==1.0.*, installed: 1.0.0]
    - alembic [required: Any, installed: 1.3.3]
      - Mako [required: Any, installed: 1.1.1]
        - MarkupSafe [required: >=0.9.2, installed: 1.1.1]
      - python-dateutil [required: Any, installed: 2.8.1]
        - six [required: >=1.5, installed: 1.14.0]
      - python-editor [required: >=0.3, installed: 1.0.4]
      - SQLAlchemy [required: >=1.1.0, installed: 1.3.13]
    - async-generator [required: >=1.8, installed: 1.10]
    - certipy [required: >=0.1.2, installed: 0.1.3]
      - pyopenssl [required: Any, installed: 19.1.0]
        - cryptography [required: >=2.8, installed: 2.8]
          - cffi [required: >=1.8,!=1.11.3, installed: 1.13.2]
            - pycparser [required: Any, installed: 2.19]
          - six [required: >=1.4.1, installed: 1.14.0]
        - six [required: >=1.5.2, installed: 1.14.0]
    - entrypoints [required: Any, installed: 0.3]
    - jinja2 [required: Any, installed: 2.11.1]
      - MarkupSafe [required: >=0.23, installed: 1.1.1]
    - oauthlib [required: >=3.0, installed: 3.1.0]
    - pamela [required: Any, installed: 1.0.0]
    - prometheus-client [required: >=0.0.21, installed: 0.7.1]
    - python-dateutil [required: Any, installed: 2.8.1]
      - six [required: >=1.5, installed: 1.14.0]
    - requests [required: Any, installed: 2.22.0]
      - certifi [required: >=2017.4.17, installed: 2019.11.28]
      - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
      - idna [required: >=2.5,<2.9, installed: 2.8]
      - urllib3 [required: >=1.21.1,<1.26,!=1.25.1,!=1.25.0, installed: 1.25.8]
    - SQLAlchemy [required: >=1.1, installed: 1.3.13]
    - tornado [required: >=5.0, installed: 6.0.3]
    - traitlets [required: >=4.3.2, installed: 4.3.3]
      - decorator [required: Any, installed: 4.4.1]
      - ipython-genutils [required: Any, installed: 0.2.0]
      - six [required: Any, installed: 1.14.0]
  - tornado [required: ==6.0.*, installed: 6.0.3]
pipdeptree==0.13.2
  - pip [required: >=6.0.0, installed: 20.0.2]
wheel==0.34.2

```

As `jupyterhub` does not pin dependencies (they only specify minimum versions for some) it means that if jinja2 releases version 3.x, it will pull that version, even if not compatible with current usage in the code. 

```
  - jupyterhub [required: ==1.0.*, installed: 1.0.0]
    - jinja2 [required: Any, installed: 2.11.1]
```

Which could be dangerous for Cylc Flow and other of our libraries that may not be compatible with latest versions. But that also means `jupyterhub` is happy if we have 2.10 installed.

**Comment by kinow** [comment]
(ps: will start reviewing dependencies to see what else can be updated in cylc-flow & cylc-uiserver, quite sure we can use 2.11 and that will fix an old issue with cylc config, but still better safe than sorry)

**Comment by hjoliver** [comment]
> This change puts Cylc Flow as the first dependency in our setup.py. This forces other dependencies that do not pin versions to use whatever Cylc Flow requires.

Nice. Is there somewhere we can document this for future reference (for the dev team) ... or is it supposed to be obvious?

**Comment by kinow** [comment]
> 
> 
> > This change puts Cylc Flow as the first dependency in our setup.py. This forces other dependencies that do not pin versions to use whatever Cylc Flow requires.
> 
> Nice. Is there somewhere we can document this for future reference (for the dev team) ... or is it supposed to be obvious?

Hmmm, good question. Not obvious I think. Only a few days ago I ordered dependencies alphabetically in some `setup.py` I think? 😓 

We could add a TODO in the `setup.py`, or we could create a quick markdown doc in this repo with development instructions, or add to the cylc-doc... what do you think would be the best place?

**Comment by hjoliver** [comment]
Hmm, yes I suppose a comment in `setup.py` would be best - and simple!

**Comment by kinow** [comment]
Added a comment in `setup.py` about the order of dependencies.

**Pull request merged**
