### PR TITLE
package the UI

### LINKED ISSUE #180: package cylc/cylc-ui
Package the UI build into this repo (from discussion on "cylc packaging" element room).

Suggestion:

* Use [cylc-ui GitHub release](https://github.com/cylc/cylc-ui/releases).
* Put the files in `cylc/uiserver/etc/ui/<version>` (to enable multiple side-by-side UI installations).
* Make this path the default in `cylc/uiserver/main.py::CylcUIServer` (for dev we will need to set the path in our user config).
* Ensure the static files are installed correctly by pypi (editable and non-editable installs), if not try using a manifest.ini file.

Future Enhancements:

* ~Automate upgrading the bundled UI version.~ - https://github.com/cylc/cylc-uiserver/issues/187
* Make the UI version configurable (perhaps add a "latest" option for convenience).
* ~(more distant future) Consider adding a simple admin command for downloading a new cylc-ui release.~ - https://github.com/cylc/cylc-uiserver/issues/186

**Pull requests welcome!**

### PR DESCRIPTION
**Pull request by oliver-sanders**
closes #180

Package the UI (currently a 0.3 prebuild) within the UIS codebase.

* By default the UIS will look for UI builds in `cylc/uiserver/ui/<version/` (configurable with the `ui_build_dir` config).
* By default the latest version will be chosen (configurable with the `ui_version` config).

After this change for UI development you must configure the `ui_build_dir` to point at your `cylc-ui/dist` directory for all installations editable or otherwise.

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Appropriate tests are included (unit and/or functional).
- [x] Appropriate change log entry included.
- [ ] configs self-documenting, opened a documentation issue to pull this into cylc-doc - https://github.com/cylc/cylc-doc/issues/222
- [x] No dependency changes.

### CODE REVIEW

**Review by kinow — APPROVED** [review]

**Comment by oliver-sanders** [comment]
(force-pushed to remove the exclusion for test files from mypy after #185 was merged)

**Comment by oliver-sanders** [comment]
How I tested that this works correctly:

1) Do a regular `pip install` (no `-e` opt):

```console
$ pip uninstall cylc-uiserver
$ pip install git+https://github.com/oliver-sanders/cylc-uiserver.git@packaging
```

2) Confirm that you have a non-editable installation:

```python
>>> import cylc.flow
>>> cylc.flow.__file__
'/Users/oliver/cylc-flow/cylc/flow/__init__.py'
>>> import cylc.uiserver
>>> cylc.uiserver.__file__
'/Users/oliver/miniconda3/envs/cylc8-2/lib/python3.7/site-packages/cylc/uiserver/__init__.py'
```

3) Run the hub:

```console
$ cylc hub
```

4) Authenticate and check UI path in the log:

```
2021-03-23 14:40:46,154 cylc.uiserver.main INFO     Starting Cylc UI Server
2021-03-23 14:40:46,154 cylc.uiserver.main INFO     Listening on port: 63087
2021-03-23 14:40:46,155 cylc.uiserver.main INFO     Serving UI from: /Users/oliver/miniconda3/envs/cylc8-2/lib/python3.7/site-packages/cylc/uiserver/ui/0.3.dev
```

The UI should be served from the path `cylc/uiserver/ui/0.3.dev`.

**Review by dwsutherland — APPROVED** [review]
Worked for me (even with the python environment pointing to my clone):
```
>>> import cylc.uiserver
>>> cylc.uiserver.__file__
'/home/sutherlander/cylc/cylc-uiserver/cylc/uiserver/__init__.py'
```
```
[I 2021-03-24T15:43:09.888 JupyterHub log:181] 200 GET /hub/spawn-pending/sutherlander (sutherlander@::ffff:127.0.0.1) 163.37ms
2021-03-24 15:43:10,242 cylc.uiserver.main INFO     JupyterHub Service Prefix: /user/sutherlander/
2021-03-24 15:43:10,250 cylc.uiserver.main INFO     Starting Cylc UI Server
2021-03-24 15:43:10,250 cylc.uiserver.main INFO     Listening on port: 52397
2021-03-24 15:43:10,251 cylc.uiserver.main INFO     Serving UI from: /home/sutherlander/.envs/uiserver/lib/python3.7/site-packages/cylc/uiserver/ui/0.3.dev
```

Will you need to rebuild and package when the beta UI comes out? (will we merge this after that? or have a new PR)

**Comment by oliver-sanders** [comment]
> Will you need to rebuild and package when the beta UI comes out? 

Yes, we should distribute the UIS with a proper UI release downloaded from the GH releases page, created a [draft] PR to automate this since it's fairly trivial https://github.com/cylc/cylc-uiserver/pull/191

**Comment by oliver-sanders** [comment]
Merging with two approvals, need to update the UI version pre-release.

**Pull request merged**
