### PR TITLE
universal id: adopt the new universal ID format

### PR DESCRIPTION
**Pull request by oliver-sanders**
* Accompanies https://github.com/cylc/cylc-flow/pull/3931
* `user|workflow|cycle|task|job` => `~user/workflow//cycle/task/job`

(tests failing until the cylc-flow branch is merged)

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Already covered by existing tests.
- [x] Appropriate change log entry included.
- [x] No documentation update required.
- [x] No dependency changes.

### CODE REVIEW

**Review by MetRonnie — APPROVED** [review]
I get test errors for `test_graphql.py` but that is the case on master too

**Review by dwsutherland — APPROVED** [review]
Looks good to me:
- Code changes.
- Works end-to-end with PR siblings (cylc-flow & cylc-ui).
- Tests work locally.

**Review by MetRonnie — APPROVED** [review]

**Review by hjoliver — APPROVED** [review]
Good to merge, along with the cylc-flow PR.

**Comment by hjoliver** [comment]
Added change log entry. Tests pass, since main cylc-flow PR merged. :tada:

**Pull request merged**
