### PR TITLE
Add graphql

### PR DESCRIPTION
**Pull request by kinow**
Fix for #11

### CODE REVIEW

**Comment by kinow** [comment]
Agreed on Riot chat to first work on this pull request that adds Tornado with Graphene/GraphQL support first. I'm creating a separate issue for adding support for WebSockets with Graphene for GraphQL subscriptions later :+1: 

Assigned @dwsutherland as one of the reviewers as we've been working together on this. The other reviewer place is up for grabs. Whoever works on this will be learning/reviewing a bit more about GraphQL and Tornado, as well as Graphene.

**Comment by kinow** [comment]
ping :grimacing:

**Comment by dwsutherland** [comment]
@kinow - Yeah I'm about onto that! I want to have a play first... Got an update and proposal for the WS data model in the pipeline.

**Comment by kinow** [comment]
Sure @dwsutheand. Just in case this one can be merged before the data model 😁

**Comment by dwsutherland** [comment]
> Sure @dwsutheand. Just in case this one can be merged before the data model 😁

@kinow - It needs to be merged first.

**Comment by dwsutherland** [comment]
And of course I can use the graphiql interface to query the Tornado server:

image

😄

**Comment by kinow** [comment]
Thanks for the thorough review @dwsutherland ! One review will do for now. We are still lacking Travis, milestones, etc, as this project is still in an early stage. Merging.

**Comment by matthewrmshin** [comment]
:+1:

**Comment by dwsutherland** [comment]
@kinow  They just merged in what I needed (for the needed server/data context):
https://github.com/graphql-python/graphene-tornado

🎉

**Comment by dwsutherland** [comment]
It's not officially released.. But I bumped the issue:
https://github.com/graphql-python/graphene-tornado/issues/13

But I'll just manually add it, and clone it into the project until then I guess..

**Comment by kinow** [comment]
>But I'll just manually add it, and clone it into the project until then I guess..

:+1: if you have troubles, we can try to use the `git` commit directly, or the branch, as dependency in `setup.py` :+1:

**Pull request merged**
