### PR TITLE
Minor improvements for pycodestyle

### PR DESCRIPTION
**Pull request by kinow**
This adds pycodestyle, and brings the changes for code style from https://github.com/cylc/cylc-uiserver/pull/34, so that they can be reviewed earlier, and #34 can be simplified for review :+1: 

We can choose a different line length later too if necessary, but given the project size (3 files), it should be fairly simple.

Bruno

### CODE REVIEW

**Comment by matthewrmshin** [comment]
Travis CI failing with pycodestyle not found?

**Comment by kinow** [comment]
>Travis CI failing with pycodestyle not found?

:rofl:

**Comment by matthewrmshin** [comment]
👍

**Comment by kinow** [comment]
Thanks!

**Pull request merged**
