### PR TITLE
Create project structure using cylc namespace

### LINKED ISSUE #25: Project structure
We are a very flat structure right now. Which works fine so far, but we are exporting two modules right now (`cylc_singleuser`, and `handlers`). If we add more files, we may end up exporting more modules.

And it is dangerous, as in the case we decide to have a file called `job`... that could be exported as `job`, and be mistakenly used when users did a `import job`.

Maybe we should use `cylc_uiserver` as top level package? Then organize our UI Server code within that folder? Me really bad choosing names, so CC'ing @cylc/core :bat:

### PR DESCRIPTION
**Pull request by kinow**
Close #25 

Uses `cylc.` namespace package, and organizes code under `cylc.uiserver`. And `cylc_singleuser.py` was renamed to `main.py`, but via `setup.py` is still exported to the user environment as `cylc-singleuser`.

I guess we can rename this script to `cylc-uiserver` or something else later - I am assuming we would need a short discussion, but otherwise if others prefer to rename it now I'm open for suggestions :grimacing: 

Cheers
Bruno

### CODE REVIEW

**Comment by kinow** [comment]
Tested locally in a new virtual environment. Tests passing, and can also successfully run `jupyterhub`. The output of `pip show -f cylc-uiserver`:

```bash
Name: cylc-uiserver
Version: 1.0
Summary: Cylc UI Server
Home-page: https://github.com/cylc/cylc-uiserver/
Author: None
Author-email: None
License: GPL
Location: /home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.7/site-packages
Requires: tornado, graphene-tornado, jupyterhub, cylc-flow
Required-by: 
Files:
  ../../../bin/cylc-singleuser
  cylc/uiserver/__init__.py
  cylc/uiserver/__pycache__/__init__.cpython-37.pyc
  cylc/uiserver/__pycache__/data_mgr.cpython-37.pyc
  cylc/uiserver/__pycache__/handlers.cpython-37.pyc
  cylc/uiserver/__pycache__/main.cpython-37.pyc
  cylc/uiserver/__pycache__/resolvers.cpython-37.pyc
  cylc/uiserver/__pycache__/workflows_mgr.cpython-37.pyc
  cylc/uiserver/data_mgr.py
  cylc/uiserver/handlers.py
  cylc/uiserver/main.py
  cylc/uiserver/resolvers.py
  cylc/uiserver/tests/__init__.py
  cylc/uiserver/tests/__pycache__/__init__.cpython-37.pyc
  cylc/uiserver/tests/__pycache__/test_handlers.cpython-37.pyc
  cylc/uiserver/tests/__pycache__/test_uiserver.cpython-37.pyc
  cylc/uiserver/tests/test_handlers.py
  cylc/uiserver/tests/test_uiserver.py
  cylc/uiserver/workflows_mgr.py
  cylc_uiserver-1.0.dist-info/COPYING
  cylc_uiserver-1.0.dist-info/INSTALLER
  cylc_uiserver-1.0.dist-info/METADATA
  cylc_uiserver-1.0.dist-info/RECORD
  cylc_uiserver-1.0.dist-info/WHEEL
  cylc_uiserver-1.0.dist-info/entry_points.txt
  cylc_uiserver-1.0.dist-info/top_level.txt
```

And copied the function from `metomi/rose` for finding the project `__version__` string.

**Comment by kinow** [comment]
(working on it now as a) there are no pull requests open, b) it needed cylc.flow namespace done first, and c) to take a break from cylc-ui and reduce changes as others are working on the UI components)

**Comment by matthewrmshin** [comment]
Looking good. I definitely prefer the command to be called `cylc-uiserver`.

**Comment by dwsutherland** [comment]
LGTM 👍

**Comment by kinow** [comment]
Ops, didn't have time to comment, but renamed `cylc-singleuser` to `cylc-uiserver` in the last commit :+1:

**Comment by dwsutherland** [comment]
> Ops, didn't have time to comment, but renamed `cylc-singleuser` to `cylc-uiserver` in the last commit, hope that's OK 👍

I saw Matts comment, and that change in the code. So figured that was ok!

**Pull request merged**
