### PR TITLE
Preparing 0.2 release

### PR DESCRIPTION
**Pull request by kinow**
This is a small change with no associated Issue.

**Requirements check-list**
- [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
- [x] Contains logically grouped changes (else tidy your branch by rebase).
- [x] Does not contain off-topic changes (use other PRs for other changes).
- [x] Does not need tests (why?).
- [x] Appropriate change log entry included.
- [x] No documentation update required.

### CODE REVIEW

**Comment by kinow** [comment]
CI will run the tests, and use the 8.0a2 from PYPI. I've installed locally to test it too.

image

Not working so well with Python 3.8.

image

The UI and UIS are working fine. Only stopping the workflows appear to be a bit buggy in Py 3.8 (got similar behavior in Py 3.10 yesterday).

**Comment by oliver-sanders** [comment]
One test failure, perhaps the exception class has changed to `SuiteStopped`?

**Comment by kinow** [comment]
> One test failure, perhaps the exception class has changed to `SuiteStopped`?

Had this same error in another pull request after I rebased it. I can have a look tomorrow morning and check if changing the exception class the test passes :+1:

**Comment by kinow** [comment]
Funny, the tests are passing locally for me with Py 3.8, when running `python setup.py test`.

The tests are also passing with same venv when I use the IDE (it runs `pytest` directly).

There must be something different in Travis CI environment.

**Comment by oliver-sanders** [comment]
Just tested locally and I can't replicate it either, ok, no need to delay this release, can fix later.

**Pull request merged**
